# Generated by Django 5.0.6 on 2024-06-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_discription_movie_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='trailer',
            new_name='trailers',
        ),
    ]
