# Generated by Django 5.0.6 on 2024-06-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
