# Generated by Django 5.0.6 on 2024-06-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_favite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favite',
        ),
    ]
